# -*- coding: utf-8 -*-
"""Amplia a obra do livro03 com parágrafos de aprofundamento + oração por capítulo,
inseridos antes de cada bloco 'O Que Observar Hoje'. Mantém a humanização (sem travessões, setas, reticências)."""
from pathlib import Path

ARQ = Path(__file__).parent.parent / "livro03_reescrito" / "obra_livro03_v2.md"
texto = ARQ.read_text(encoding="utf-8")

EXTRAS = {
"Capítulo 1: A Mente que o Mundo Moldou": """Existe um exercício simples que revela a diferença entre a mente moldada e a mente renovada. Feche os olhos por um instante e lembre-se de um momento em que você se sentiu em paz, protegido e completo. Não importa se foi na infância, numa manhã de domingo ou num instante de oração. Naquele momento, seus pensamentos não estavam correndo, seu coração não estava inquieto, e a vida parecia simples. Aquela paz não dependia de nada externo, ela brotava de dentro. A mente moldada diz que aquele momento passou e não volta mais. A mente renovada reconhece que aquela paz nunca partiu, apenas foi coberta por camadas de pensamento condicionado. E o que foi coberto pode ser descoberto novamente.

O processo de descoberta começa com pequenas escolhas diárias. Quando você acorda e o primeiro pensamento é de preocupação, pode escolher, naquele instante, lembrar-se de Deus e entregar o dia em suas mãos. Quando uma notícia difícil chega, pode escolher não construir cenários de desastre antes de orar. Quando alguém o critica, pode escolher não alimentar a ferida, mas perguntar o que o amor faria. Cada escolha dessas é um tijolo na construção de uma mente nova. E como toda construção, exige paciência e constância. Nenhuma parede se ergue em um dia, mas todas as paredes se erguem um tijolo por vez.

O Senhor conhece sua luta e caminha com você nela. Ele não se afasta quando a mente se agita, nem se decepciona quando você cai nos velhos padrões. Ele espera, como o pai da parábola, com os braços abertos e o coração cheio de amor. A cada retorno, a cada tentativa, a cada pequena vitória interior, Ele se alegra. Porque não é a perfeição que Ele busca em você, é a direção. E a direção da sua alma, mesmo entre tropeços, é a direção da luz.

Oração do Capítulo: Senhor, ajuda-me a reconhecer que não sou meus pensamentos. Ensina-me a observar a mente com serenidade e a escolher, dia após dia, o pensamento que vem de ti. Tira de mim o peso do condicionamento e revela a paz que sempre esteve em meu interior. Em nome de Jesus, amém.""",

"Capítulo 2: O Convite que Vem de Dentro": """Muitas pessoas esperam ouvir a voz de Deus em trovões ou em grandes sinais, mas a voz do chamado interior quase sempre chega em sussurros. Chega numa inquietação que não tem nome, numa tristeza que não tem causa, num desejo de sentido que as conquistas não satisfazem. Chega no silêncio da noite, quando o mundo se aquieta e a alma finalmente pode ser ouvida. Quem aprende a escutar esse sussurro descobre que Deus nunca esteve calado, apenas foi ignorado por uma mente ocupada demais para ouvir.

Para responder ao convite que vem de dentro, é preciso criar espaço para o silêncio. Não o silêncio vazio, mas o silêncio atento, aquele em que você se recolhe, respira e simplesmente está na presença. Cinco minutos de silêncio sincero valem mais do que horas de agitação. Nesses minutos, a voz interior ganha clareza, as decisões encontram direção e a alma reconhece o caminho de casa. Jesus costumava se retirar para lugares desertos e orar, não por hábito, mas por necessidade. Se ele, sendo quem era, precisava desse recolhimento, quanto mais nós.

Talvez você esteja adiando esse recolhimento por achar que não tem tempo. Mas o tempo existe, ele apenas está ocupado com coisas que não alimentam a alma. O convite que vem de dentro pede que você reorganize o tempo, não para fazer mais, mas para ser mais. Para estar mais presente, mais consciente, mais vivo. E nesse estar, a vida se reorganiza por dentro, e o que parecia urgente perde a pressa, o que parecia pesado perde o peso, o que parecia sem sentido encontra propósito.

Oração do Capítulo: Pai, eu quero ouvir tua voz. Dá-me sabedoria para criar espaço de silêncio em minha rotina e coragem para responder ao teu chamado. Mostra-me o caminho de volta para casa, para a paz que só tu podes dar. Em nome de Jesus, amém.""",

"Capítulo 3: Não Vos Conformeis": """A renovação da mente não é um evento que acontece uma única vez, é um estilo de vida. Assim como o corpo precisa de alimento diário, a mente renovada precisa de alimento diário. Esse alimento é a Palavra de Deus, a oração, a reflexão, a companhia de pessoas que apontam para o alto, a prática consciente do bem. Sem esse alimento, a mente condicionada retoma o comando, não porque seja mais forte, mas porque está mais acostumada. A mente renovada é como um jardim novo: precisa ser cuidada todos os dias, senão as ervas do pensamento antigo voltam a crescer.

Por isso, não se surpreenda se, mesmo após grandes progressos, velhos pensamentos aparecerem. Eles não são um sinal de fracasso, são um sinal de que a batalha é contínua. O que importa é não deixá-los florescer. Quando um pensamento de medo aparece, você não precisa se desesperar, basta não o alimentar. Quando uma lembrança de culpa surge, você não precisa revivê-la, basta soltá-la. A mente renovada não é uma mente sem tentações, é uma mente que aprendeu a escolher. E cada escolha fortalece a próxima.

Existe também uma dimensão comunitária nessa renovação. Ninguém caminha sozinho até o reino. A comunhão com outros que buscam a mesma verdade sustenta, encoraja e ilumina. Uma palavra de irmão na fé, uma oração compartilhada, um testemunho de superação, tudo isso é alimento para a mente renovada. Busque estar perto de quem aponta para Deus, e deixe que sua presença também seja luz para outros. Porque o reino se constrói em comunidade, e a mente renovada floresce no solo do amor fraterno.

Oração do Capítulo: Senhor, renova minha mente todos os dias. Alimenta-me com tua Palavra, sustenta-me na oração e coloca ao meu lado irmãos que caminhem contigo. Não permitas que eu me conforme com o mundo, mas transforma-me pela renovação do meu pensamento. Em nome de Jesus, amém.""",

"Capítulo 4: A Mente que Houve em Cristo": """Para compreender a mente de Cristo, é preciso compreender o que ele valorizava. Jesus não valorizava o poder humano, a fama ou a posse. Valorizava a verdade, a compaixão, o serviço, a unidade com o Pai. Quando tentaram envolvê-lo em disputas políticas, ele se recusou. Quando quiseram fazê-lo rei, ele se retirou. Quando o tentaram com o poder do mundo, ele respondeu com a Palavra. A mente de Cristo não é atraída pelas coroas do mundo, porque já conhece uma glória maior, a glória do amor que se doa.

Adotar essa mente significa reordenar valores. Não se trata de abandonar as responsabilidades do mundo, mas de colocá-las sob a luz do espírito. O trabalho, a família, os estudos, os projetos, tudo pode ser vivido com a mente de Cristo quando a intenção é purificada. Trabalhar não para acumular, mas para servir. Cuidar da família não por obrigação, mas por amor. Estudar não para competir, mas para crescer e ajudar. Cada área da vida se torna sagrada quando é vivida a partir da consciência de unidade com Deus.

A mente de Cristo também transforma a relação com o sofrimento. Jesus não prometeu uma vida sem dores, prometeu uma presença que sustenta na dor. Ele mesmo passou pela cruz, não como derrota, mas como passagem para uma vida maior. Quem pensa com a mente de Cristo não nega o sofrimento, mas o atravessa com fé, sabendo que a dor não é o fim, que a noite não é eterna e que a ressurreição é a verdade final de toda vida entregue a Deus. Essa certeza não elimina as lágrimas, mas enxuga o coração e devolve a esperança.

Oração do Capítulo: Senhor Jesus, dá-me a tua mente. Ensina-me a pensar como tu pensas, a valorizar o que tu valorizas, a amar como tu amas. Purifica minhas intenções e ajuda-me a viver cada área da minha vida a partir da unidade com o Pai. Em nome de Jesus, amém.""",

"Capítulo 5: O Reino de Deus Está Dentro de Vós": """O reino de Deus dentro de você não compete com o mundo exterior, ele o ilumina. Quando você descobre esse reino interior, não precisa fugir das responsabilidades, pelo contrário, passa a vivê-las de outra forma. O trabalho se torna serviço, a família se torna escola de amor, as dificuldades se tornam oportunidades de manifestar a paz que habita em você. O reino não o afasta do mundo, o reino o envia ao mundo como portador de luz, como a cidade sobre o monte que não pode ser escondida.

Existe um teste prático para perceber se você está vivendo a partir do reino interior: observe sua reação diante da pressão. Quando tudo está calmo, qualquer um parece sereno. Mas quando a pressão chega, quando o prazo aperta, quando a pessoa difícil aparece, quando o imprevisto acontece, o que surge de você? Se surge paz, paciência e clareza, é sinal de que o reino está governando. Se surge ansiedade, irritação e confusão, é sinal de que a mente moldada ainda está no comando. A boa notícia é que essa observação não é um julgamento, é um mapa: ela mostra exatamente onde o reino precisa ser mais reconhecido.

Cultivar o reino interior é como guardar um tesouro. O tesouro não se mostra a todos, guarda-se no coração. Em segredo, você ora, agradece, silencia, confia. E dessa intimidade com Deus, brota uma força que o mundo não vê, mas sente. As pessoas percebem quando alguém carrega o reino por dentro: há uma serenidade que não se explica, uma bondade que não se finge, uma presença que abençoa. Não tente fabricar essa presença, apenas cultive o tesouro, e ela fluirá naturalmente.

Oração do Capítulo: Pai, ajuda-me a descobrir o reino que está dentro de mim. Que eu não busque fora o que já recebi dentro. Que minha paz não dependa das circunstâncias, mas da tua presença. E que, vivendo a partir do reino, eu seja luz para aqueles que ainda o procuram longe. Em nome de Jesus, amém.""",

"Capítulo 6: Como um Homem Pensa, Assim Ele É": """A lei do pensamento exige honestidade. Não adianta declarar pensamentos de abundância enquanto o coração está cheio de medo da falta. A mente renovada não é construída sobre mentiras, mas sobre verdades mais profundas. Quando a aparência diz falta, a verdade espiritual diz que Deus é a fonte de toda provisão. Quando a aparência diz doença, a verdade espiritual diz que a vida de Deus flui em você. Quando a aparência diz fracasso, a verdade espiritual diz que você é amado e sustentado, e que cada passo é aprendizado. Declarar essas verdades não é negar a realidade, é afirmar a realidade mais alta.

Para que a lei do pensamento trabalhe a seu favor, é preciso também vigiar as imagens mentais. A mente trabalha com imagens: você se vê saudável ou doente, próspero ou carente, vitorioso ou derrotado? Essas imagens, repetidas com emoção, moldam a experiência. Por isso, a prática de visualizar o bem é tão antiga quanto a própria Escritura: "Aquilo que a minha alma desejou, isso eu vi". Não se trata de fantasia, trata-se de alinhar a mente com o que Deus já deseja para você, que é vida, paz e abundância de amor.

A persistência é a chave dessa prática. A mente condicionada resiste à mudança, porque a mudança exige esforço e a resistência é cômoda. Nos primeiros dias, os pensamentos novos podem parecer estranhos, e os velhos, mais fortes. Não desista. A semente leva tempo para germinar, mas germina. Continue escolhendo a verdade, continue alimentando a fé, continue agradecendo antes de ver. E um dia, sem que você perceba exatamente quando, a mente renovada se torna sua natureza, e os pensamentos de fé fluem com a naturalidade de quem respira.

Oração do Capítulo: Senhor, guarda minha mente e direciona meus pensamentos. Ajuda-me a pensar a verdade, a alimentar imagens de vida e a persistir na fé mesmo quando a aparência contradiz. Que eu seja aquilo que penso em meu coração, e que meu coração pense contigo. Em nome de Jesus, amém.""",

"Capítulo 7: O Poder da Palavra e da Fé": """As palavras têm um poder que raramente medimos. Uma palavra dita no momento certo pode curar uma alma; uma palavra dita no momento errado pode ferir por anos. Por isso, as Escrituras comparam a língua a um fogo, pequeno, mas capaz de incendiar uma floresta inteira. A mente renovada vigia as palavras, não por medo, mas por amor. Sabe que cada palavra é uma semente, e escolhe plantar sementes de bênção, de verdade e de esperança.

Existe uma prática simples e poderosa: abençoar. Em vez de criticar, abençoar. Em vez de reclamar, abençoar. Em vez de amaldiçoar as circunstâncias, abençoá-las, pedindo a Deus que transforme o que parece mal em bem. A bênção não muda as circunstâncias por magia, mas muda a mente que as enfrenta, e a mente transformada transforma a experiência. Abençoe sua casa, seu trabalho, sua família, seu futuro. Abençoe até os desafios, porque eles são mestres disfarçados. E perceba como a atmosfera ao seu redor se torna mais leve e mais fértil.

A fé, por sua vez, se fortalece no exercício. Fé não é um dom que se recebe pronto, é um músculo que se desenvolve. Cada vez que você confia em Deus numa situação difícil e observa o cuidado dele, a fé cresce. Cada vez que você ora e percebe a resposta, a fé se firma. Cada vez que você escolhe a esperança em vez do desespero, a fé se torna mais natural. Não espere ter uma fé grande para começar; comece com a fé pequena, do tamanho de um grão de mostarda, e deixe que ela cresça no solo da prática constante.

Oração do Capítulo: Senhor, coloca guarda em meus lábios. Que minhas palavras sejam sementes de bênção e que minha fé cresça a cada dia no exercício da confiança. Ensina-me a falar a verdade com amor e a crer no que ainda não vejo, porque tudo é possível ao que crê. Em nome de Jesus, amém.""",

"Capítulo 8: Arrependei-vos: a Mudança de Mente": """A metanoia, a mudança de mente, tem um efeito imediato: a libertação do passado. A mente condicionada vive presa ao passado, revisitando erros, alimentando ressentimentos, repetindo histórias de vitimização. Cada visita ao passado é como reabrir uma ferida que já cicatrizou. A mudança de mente corta esse ciclo: reconhece o erro, aprende a lição, agradece o aprendizado e segue em frente. O passado não é apagado, mas perde o poder de governar o presente. E o presente, liberto do passado, torna-se o lugar onde o reino se manifesta.

A mudança de mente também transforma a relação com o futuro. A mente condicionada teme o futuro, projeta nele todos os medos do passado. A mente renovada entrega o futuro a Deus, sabendo que quem cuidou de você até hoje cuidará de amanhã. Essa entrega não é passividade, é confiança ativa. Você faz a sua parte, planta as sementes, cuida do jardim, e deixa a colheita nas mãos do Senhor. E nessa confiança, a ansiedade perde o espaço e a paz toma posse.

Cada dia é uma nova oportunidade de metanoia. Ao acordar, você pode escolher: continuar pensando como pensou ontem, ou abrir-se para uma mente nova. As Escrituras dizem que as misericórdias do Senhor se renovam cada manhã. E junto com elas, a oportunidade de renovar a mente. Não importa o que aconteceu ontem, hoje é um dia novo, uma mente nova, uma chance nova. Aproveite essa chance, não para se culpar pelo que passou, mas para caminhar na direção que o espírito aponta, com a leveza de quem foi perdoado e a alegria de quem recomeça.

Oração do Capítulo: Senhor, renova minha mente nesta manhã. Liberta-me do peso do passado e da ansiedade pelo futuro. Ensina-me a viver o presente contigo, com a leveza de quem é perdoado e a esperança de quem recomeça. Em nome de Jesus, amém.""",

"Capítulo 9: Vós Sois a Luz do Mundo": """A luz não precisa anunciar a si mesma, ela simplesmente brilha. Uma pessoa que vive a partir da mente renovada não precisa se vangloriar de sua fé, não precisa expor suas orações, não precisa demonstrar sua bondade. A luz da sua vida fala por si. As pessoas percebem quando alguém é verdadeiro, quando alguém carrega paz, quando alguém ama sem segundas intenções. E essa percepção é um testemunho mais poderoso do que mil discursos. Viva de tal forma que sua vida seja o sermão mais convincente que você já pregou.

Jesus alertou, porém, sobre a falsa luz: a daqueles que fazem boas obras para serem vistos pelos homens. Essa luz é artificial, alimentada pela vaidade, e se apaga quando a plateia desaparece. A luz verdadeira não depende de reconhecimento, porque sua fonte é interior. Ela brilha no escondido, na oração secreta, na bondade anônima, no serviço silencioso. E quanto mais desinteressada, mais pura e mais forte. Não busque aplausos, busque fidelidade. A luz que agrada a Deus é a que brilha para Deus, e essa, ninguém apaga.

Há momentos em que a luz parece fraca, quando a tristeza cobre, quando o cansaço pesa, quando a fé vacila. Nesses momentos, lembre-se: a luz não deixa de existir quando é coberta, apenas fica oculta. Uma nuvem pode cobrir o sol, mas o sol continua brilhando acima dela. Sua alma continua luz, mesmo quando você não a sente. Descanse nessa verdade, espere a nuvem passar, e não se condene pela fraqueza momentânea. Até a luz mais firme conhece o alívio de descansar. E depois do descanso, brilha com renovado vigor.

Oração do Capítulo: Senhor, que minha vida seja luz para o mundo, não por vaidade, mas por fidelidade. Que eu brilhe no escondido e no visível, sem buscar aplausos, apenas refletindo tua glória. E nos dias de nuvem, lembra-me de que a luz continua, e que ela voltará a brilhar. Em nome de Jesus, amém.""",

"Capítulo 10: O Olho Único e o Coração Limpo": """O olho único começa pelo olhar para si mesmo. Muitas pessoas são mestras em ver os defeitos alheios e cegas para as próprias sombras. A mente renovada começa o exame por dentro: que pensamentos eu alimento, que intenções eu carrego, que máscaras eu uso? Esse exame não é para condenação, é para purificação. Quando a luz interior é limpa, a visão exterior se clareia. E o que antes via inimigos por toda parte, começa a ver irmãos em jornada, expressões do mesmo espírito em diferentes estágios de despertar.

A pureza de coração é uma conquista diária, não um estado definitivo. O coração se suja com o julgamento, com a inveja, com o ressentimento, com a duplicidade. E se limpa com o perdão, com a gratidão, com a sinceridade, com a oração. Cada noite, ao deitar, pode-se examinar o coração do dia e entregar a Deus o que não pertence a Ele. Cada manhã, ao acordar, pode-se pedir um coração novo, limpo, pronto para ver a Deus no dia que começa. Essa higiene espiritual é tão importante quanto qualquer cuidado físico.

Quando o olho é único, a vida se simplifica. Deixam de existir as mil interpretações do medo, e passa a existir uma única visão: a verdade. Deixam de existir os mil julgamentos sobre as pessoas, e passa a existir um único reconhecimento: Deus em todos. Deixam de existir as mil preocupações com o futuro, e passa a existir uma única confiança: Deus no controle. Essa simplificação não empobrece a vida, a enriquece imensamente, porque concentra as forças naquilo que realmente importa e liberta a alma do peso do que não importa.

Oração do Capítulo: Senhor, purifica meu olhar e meu coração. Tira de mim o julgamento, o ressentimento e a duplicidade. Dá-me o olho único, que vê a verdade, e o coração limpo, que vê a ti. Que minha vida seja simples, luminosa e verdadeira, como a cidade sobre o monte. Em nome de Jesus, amém.""",

"Capítulo 11: Orai Sem Cessar": """Para viver em oração contínua, é preciso transformar a própria noção de tempo. O tempo do relógio é linear: momentos sagrados e momentos comuns. O tempo do espírito é contínuo: tudo é sagrado, tudo é encontro. Quem ora sem cessar não precisa separar um momento para Deus, porque todos os momentos são Dele. Isso não elimina a importância do recolhimento diário, que alimenta essa consciência. O recolhimento é o encontro com a fonte, e a vida inteira é o rio que flui dessa fonte. Sem encontro, o rio seca. Sem fluxo, o encontro fica estagnado. Os dois se alimentam.

Na prática, orar sem cessar significa manter o coração em diálogo constante. Não apenas palavras, mas atitude. Diante de uma decisão, um pensamento rápido: Senhor, me guia. Diante de uma preocupação, uma entrega: Senhor, contigo eu deixo. Diante de uma alegria, uma gratidão: Senhor, obrigado. Diante de uma pessoa, uma bênção silenciosa. Esses pequenos atos, repetidos ao longo do dia, mantêm a alma conectada, como um fio que nunca se rompe entre o coração e Deus.

Existe uma beleza especial nessa oração contínua: ela santifica o cotidiano. O trabalho deixa de ser apenas trabalho e se torna serviço oferecido a Deus. As tarefas domésticas deixam de ser obrigação e se tornam cuidado amoroso. Os encontros casuais deixam de ser acaso e se tornam providência. A pessoa que ora sem cessar descobre que não há vida comum, há vida sagrada vista com olhos renovados. E essa descoberta transforma até os dias mais simples em festa, porque a presença de Deus os atravessa do começo ao fim.

Oração do Capítulo: Senhor, ensina-me a orar sem cessar. Que meu coração esteja em diálogo contigo em cada momento, em cada tarefa, em cada encontro. Santifica meu cotidiano e faz de toda a minha vida uma oração viva. Em nome de Jesus, amém.""",

"Capítulo 12: Jesus e a Lei Mental": """A lei mental não é uma descoberta moderna, é um princípio tão antigo quanto a própria criação. As Escrituras dizem que Deus criou o mundo pela palavra, e que o ser humano, feito à sua imagem, também cria pela palavra e pelo pensamento. A lei não é uma novidade, é uma revelação: aquilo que sempre funcionou, mas nem sempre foi compreendido, foi explicado e demonstrado por Jesus de forma acessível a todos. Ele não veio abolir a lei, veio cumpri-la e revelá-la em sua plenitude.

Compreender a lei mental não significa reduzir Deus a uma fórmula. Deus é infinitamente mais do que qualquer lei que o descreva, assim como o oceano é infinitamente mais do que qualquer onda. A lei é a forma como o amor de Deus opera na consciência humana, um convite à cooperação. Quando você alinha pensamentos, palavras e fé com o bem, está cooperando com a corrente divina em vez de nadar contra ela. E a corrente, que sempre esteve ali, o carrega com menos esforço e mais graça.

Existe também um aspecto de responsabilidade nessa lei. Se a mente cria, então é preciso cuidar do que se pensa. Se a palavra molda, é preciso vigiar o que se fala. Essa responsabilidade não é um fardo, é uma liberdade: significa que você não é vítima indefesa das circunstâncias, mas participante consciente da própria experiência. Significa que a mudança começa em você, no lugar mais acessível que existe, a sua própria mente. E essa mudança, por menor que pareça, tem o poder de transformar a vida inteira, porque a vida inteira flui da mente.

Oração do Capítulo: Senhor, ensina-me a cooperar com tuas leis espirituais. Ajuda-me a semear bons pensamentos, boas palavras e boa fé. Dá-me a responsabilidade alegre de cocriar minha experiência contigo, e a sabedoria de colocar tudo sob tua vontade. Em nome de Jesus, amém.""",

"Capítulo 13: A Mente Renovada e o Corpo Saudável": """A relação entre mente e corpo não é uma fantasia esotérica, é uma realidade observável. A alegria fortalece, a preocupação enfraquece, o perdão relaxa, o ressentimento tensiona, a esperança sustenta, o desespero consome. Quem cuida apenas do corpo, negligenciando a mente, cuida do efeito sem cuidar da causa. Quem renova a mente, por outro lado, oferece ao corpo o melhor remédio que existe: uma consciência em paz. E sobre uma consciência em paz, até os cuidados médicos produzem melhores resultados.

Isso não significa abandonar a medicina ou os cuidados com o corpo. O corpo é templo do Espírito, e como templo, merece cuidado, alimento, descanso e atenção. A medicina é uma bênção de Deus, e usá-la com gratidão é parte da sabedoria. O que a mente renovada acrescenta é a dimensão espiritual da cura: a confiança de que Deus é o médico dos médicos, a certeza de que a vida de Deus flui em cada célula, a serenidade que permite ao corpo fazer o seu trabalho de restauração sem a interferência do medo.

Há um testemunho antigo que atravessa gerações: muitos encontraram cura quando abandonaram o medo da doença e se voltaram para a vida de Deus. Não porque a doença fosse ilusão, mas porque o medo alimentava a doença e a fé fortaleceu a vida. A mente renovada não nega o sintoma, mas recusa-se a dar-lhe o último poder. Coloca-o diante de Deus, entrega a cura, e continua vivendo com fé, gratidão e esperança, sabendo que a vida é mais forte que a doença, porque a vida é Deus.

Oração do Capítulo: Senhor, tu és o médico de minha alma e de meu corpo. Renova minha mente e sara minhas emoções, para que meu corpo reflita tua paz. Dá-me sabedoria para cuidar do templo e fé para confiar em tua cura. Que a vida de Deus flua em mim, agora e sempre. Em nome de Jesus, amém.""",

"Capítulo 14: Não Temas, Apenas Crê": """O medo tem uma voz insistente, mas também tem um ponto fraco: ele não resiste à verdade declarada. Quando o medo diz "você vai falhar", a verdade responde "Deus está comigo e me guia". Quando o medo diz "você está sozinho", a verdade responde "nunca te deixarei, nunca te desampararei". Quando o medo diz "não há saída", a verdade responde "para Deus todas as coisas são possíveis". A fé não é ausência de medo, é a escolha de responder ao medo com a verdade, até que a verdade se torne mais real que o medo.

Existe também o medo que se disfarça de prudência. Ele se apresenta como cautela, como realismo, como preocupação legítima. Mas por baixo da máscara, é o mesmo medo: a desconfiança de que Deus não cuidará. A prudência verdadeira não exclui a fé, ela caminha com a fé. Cuida-se do que é possível, e confia-se no que é de Deus. Semeia-se com diligência, e espera-se com paciência. A fé não é imprudência, é confiança que age. Ela faz a sua parte e deixa o restante nas mãos do Senhor, sem ansiedade.

Para vencer o medo, é útil também lembrar as vitórias passadas. Cada dificuldade superada é uma prova viva do cuidado de Deus. O deserto atravessado, a provisão que chegou, a força que apareceu quando parecia não haver, tudo isso é memorial. Quando o medo vier, recorra ao memorial: Deus já cuidou, Deus cuida, Deus cuidará. Ele não mudou, não se cansou, não se esqueceu de você. E o mesmo Deus que abriu caminho ontem abrirá amanhã. Não temas, apenas crê.

Oração do Capítulo: Senhor, quando o medo bater à porta, envia a fé para atender. Lembra-me das tuas vitórias em minha vida e da tua promessa de nunca me desamparar. Dá-me a coragem de crer mesmo sem ver, e a paz de saber que estás no controle. Em nome de Jesus, amém.""",

"Capítulo 15: Cristo em Vós, a Esperança da Glória": """Viver a partir de Cristo em você muda inclusive a forma de lidar com os limites humanos. Você não precisa mais provar nada, porque já é amado. Não precisa mais competir, porque já é completo. Não precisa mais se esconder, porque já é conhecido e aceito. Essa liberdade interior é uma das maiores dádivas da vida espiritual. Ela não gera orgulho, gera gratidão e serviço. Quem sabe que carrega um tesouro não se vangloria do tesouro, apenas o guarda com cuidado e o compartilha com generosidade.

A presença de Cristo em você também transforma o sofrimento. As dores continuam a existir, mas deixam de ser sem sentido. Elas se tornam participação, como disse Paulo: "completo na minha carne o que resta das aflições de Cristo". Isso não significa que Deus deseja seu sofrimento, significa que o sofrimento, vivido com fé, produz frutos: paciência, caráter, esperança, compaixão. A alma que sofre com Cristo aprende a consolar os que sofrem, e o consolo recebido se torna consolo oferecido. A dor não é desperdiçada, é transformada em ministério.

Há também uma dimensão de confiança nessa presença. Se Cristo vive em você, então você não precisa carregar sozinho o peso da vida. Ele carrega com você, dentro de você. As decisões podem ser compartilhadas em oração, as forças podem ser renovadas na presença, os medos podem ser entregues no silêncio. E o que parece impossível para você, torna-se possível na união. Não porque você ficou mais forte, mas porque a fonte de toda força habita em você, e a fonte não se esgota, não se cansa, não falha.

Oração do Capítulo: Senhor, que Cristo viva em mim e eu viva a partir dele. Liberta-me da necessidade de provar, competir e esconder, porque já sou amado. Transforma minhas dores em frutos e minhas fraquezas em canais da tua força. Que a esperança da glória se manifeste em minha vida, para tua glória e para o bem de muitos. Em nome de Jesus, amém.""",

"Capítulo 16: O Poder da Gratidão": """A gratidão também é uma forma de memória sagrada. Quando você agradece, recorda as bondades de Deus e impede que o coração se endureça. O povo de Israel foi instruído a lembrar, a erguer memoriais, a contar às crianças as maravilhas do Senhor, precisamente para não esquecer. O coração que esquece as bondades torna-se ingrato e frágil. O coração que lembra e agradece torna-se forte e confiante. Cultivar a gratidão é cultivar a memória do bem, e essa memória é um escudo contra o desânimo.

Nos dias difíceis, a gratidão pode parecer impossível, mas é exatamente aí que ela mais importa. Não se trata de agradecer pela dor, mas de agradecer apesar dela, de buscar o bem que permanece mesmo na tempestade. Existe sempre algo pelo que agradecer: a vida que continua, a fé que resiste, o amor que não falha, a promessa que permanece. Esse exercício não nega a dor, mas impede que ela ocupe todo o espaço do coração. E no espaço preservado pela gratidão, a esperança continua a respirar.

A gratidão também multiplica. Quem agradece pelo pouco que tem, recebe condições de receber mais, porque a gratidão abre o coração e o coração aberto é capaz de acolher. Quem reclama do pouco, fecha-se e não percebe as bênçãos que passam. Essa não é uma lei de troca, é uma lei de atenção: a mente agradecida vê o bem que a mente reclamante ignora. E o bem visto, reconhecido e agradecido, floresce. Comece a agradecer pelo que você tem, e descobrirá que tem mais do que pensava, e que o mais continua chegando.

Oração do Capítulo: Senhor, dá-me um coração grato em todos os dias, nos fáceis e nos difíceis. Ensina-me a lembrar tuas bondades e a reconhecer o bem que permanece. Que a gratidão abra meu coração, multiplique minha percepção e transforme minha vida em louvor. Em nome de Jesus, amém.""",

"Capítulo 17: A Unidade com Deus e a Paz que Excede o Entendimento": """A unidade com Deus não elimina as diferenças entre as pessoas, ela as harmoniza. Quando você se reconhece um com Deus, passa a reconhecer a mesma presença nos outros, e as diferenças, que antes separavam, passam a enriquecer. O irmão que pensa diferente não é mais ameaça, é complemento. A pessoa que erra não é mais inimiga, é aprendiz como você. A família, a igreja, a sociedade, tudo se torna um corpo com muitos membros, cada um com seu dom, todos alimentados pela mesma vida. Essa visão de unidade é o fermento que transforma as relações.

A paz que excede o entendimento não se explica, se experimenta. Ela é sentida na calma que permanece quando o caos se instala, na confiança que sustenta quando as respostas faltam, na alegria que resiste quando as lágrimas caem. Essa paz não vem de fora, vem da união interior com a fonte de toda paz. E ela se renova na oração, se fortalece na gratidão, se aprofunda no silêncio. Quem a possui carrega um tesouro que ninguém pode roubar, porque não está guardado em lugar algum do mundo, mas no coração, junto a Deus.

Ao terminar esta leitura, lembre-se de que o livro não é um fim, é um começo. A mente renovada se constrói na prática diária, na oração constante, na gratidão perseverante. Volte a estes capítulos quantas vezes precisar, não como quem repete uma lição, mas como quem rega um jardim. Cada leitura pode revelar algo novo, porque a verdade é inesgotável. E a cada retorno, a paz se aprofunda, a visão se clareia, a unidade se fortalece. Que esta obra seja uma companheira fiel em sua jornada, e que a mente de Cristo, que é a esperança da glória, brilhe cada vez mais em você.

Oração do Capítulo: Pai, eu te agradeço por esta jornada de renovação. Que a unidade contigo se aprofunde em mim a cada dia, e que tua paz, que excede todo entendimento, guarde meu coração e minha mente em Cristo Jesus. Faze de mim um canal do teu amor e uma testemunha da tua luz, agora e para sempre. Em nome de Jesus, amém.""",
}

for titulo, extra in EXTRAS.items():
    marcador = f"**O Que Observar Hoje:**"
    # localiza o capítulo e insere o extra antes do bloco O Que Observar Hoje do capítulo
    idx_titulo = texto.find(f"## {titulo}")
    if idx_titulo == -1:
        print("NÃO ACHOU:", titulo)
        continue
    idx_obs = texto.find(marcador, idx_titulo)
    if idx_obs == -1:
        print("NÃO ACHOU bloco em:", titulo)
        continue
    texto = texto[:idx_obs] + extra.strip() + "\n\n" + texto[idx_obs:]

ARQ.write_text(texto, encoding="utf-8")
print("Concluído. Extras inseridos em", len(EXTRAS), "capítulos.")
